spring.application.name=UTNClimalert

spring.datasource.url=jdbc:h2:mem:climalertdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update

# Configuracion API clima
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.key=a32647ba047f4150a4b01311260807
weather.location=CABA

# Configuracion Mail, datos de ejemplo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mi_correo@gmail.com
spring.mail.password=12345
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true